### ISSUE TITLE
404 for wiki

### ISSUE THREAD

**Issue by nuke-web3** [commons-stack/wiki#4]
> Live on https://commons-stack.gitbook.io/wiki/

This link 404s (in top line description on this repo, not the readme)

Do you mean this?
https://wiki.commonsstack.org/

**Comment by nuke-web3** [comment]
@GriffGreen ?

**Comment by jpitts** [comment]
Ping about the broken link. Should be a quick update for someone w/ access to the repo.

"Live on https://commons-stack.gitbook.io/wiki/"
